# Generated by Django 5.2 on 2025-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('priority', '-deadline', 'name')},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgent!!!'), ('HIGH', 'High!'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10),
        ),
    ]
