# Generated by Django 5.2 on 2025-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('-position', 'first_name', 'last_name')},
        ),
    ]
